name: Build and Deploy Angular App to Azure App Service

on:
  push:
    branches:
      - main  # Cambia esto por el nombre de tu rama principal si es diferente

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: |
        # Personalizar el comando de instalación
        npm install --force

    - name: Build Angular App
      run: |
        # Cambia la configuración si es necesario (por ejemplo, si usas una configuración específica de entorno)
        npm run build -- --prod

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: <your-app-name>  # Reemplaza con el nombre de tu aplicación en Azure App Service
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Agrega este secreto en la configuración de tu repositorio en GitHub
        package: ./dist/pakay  # Reemplaza con el nombre de tu carpeta de aplicación dentro de la carpeta "dist"
